language: ruby
rvm:
- 2.2.3
- 2.1.0
cache: bundler
script:
- bundle exec rspec spec
notifications:
  webhooks:
    secure: PZ9zkk1aar0shHE87JpIE9+OgjTgYFoiK0cP+jNcuF/GjhVaypkaieKzCRldERkkz2YEi2eIqgKhybQpYAcG4q1vhpjiBpOOdLYmTsRFCSoDwt8fAlC9JRI3+D6nc4hF1y8ds9aVoYQVfCcGasIOH4KAKMbKGviPgyFIhdbIbDw=
